Feat/schrijf testen soj 36
Avans-290IN4SOj-Scouting/Scouting pull request #104
Opened 2024-05-20 20:40 UTC by VindSent

2024-05-20 20:43 UTC, VindSent commented on app/Models/Order.php
> -    protected $fillable = [
Ik weet niet waarom er alweer een tweede fillable is, maar beide kwamen overeen met de kolommen uit de db (hadden meer of minder). Nu klopt het, op de timestaps na.

2024-05-22 10:10 UTC, linderus requested changes
Je hebt onnodige changes doordat de parent branch niet up to date is met dev, verder doen alle testen het bij mij

2024-05-22 10:15 UTC, VindSent commented
> Je hebt onnodige changes doordat de parent branch niet up to date is met dev, verder doen alle testen het bij mij

![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/104061744/c66b3464-50bd-4054-be76-e85bf145526e)

Mijn main branch is up to date. Denk niet dat het ligt aan mijn sub branch die niet up to date is met develop.

2024-05-22 11:20 UTC, linderus commented
Hier gaat wsl wat mis: 
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/130562052/02710c8c-6b18-4a84-b21a-9ef45fcc6412)

2024-05-22 17:27 UTC, linderus approved these changes
Prima zo

2024-05-22 17:44 UTC, merged