feat(mail): SOJ-370 and SOJ-371
Avans-290IN4SOj-Scouting/Scouting pull request #115
Opened 2024-06-04 12:26 UTC by VindSent

Naast de US heb ik ook nog de mail aangepast wanneer de gebruiker zijn eigen order annuleert. 

### - Mail versturen bij bestelling plaatsen
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/104061744/26ae8bba-23ea-42e2-bf6d-a30180c59b44)

 ### - Mail sturen bij status verandering
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/104061744/ceff42f7-ad00-4fbf-ab48-88f2927f8b37)

 ### - Mail sturen bij bestelling annuleren
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/104061744/c9c50da3-73e5-4500-a233-5c2b7ecf580c)

2024-06-13 16:39 UTC, Auwburn requested changes
Ik kon zelf niet de mail bekijken, omdat de mails het niet doen bij mij (heb hier wel meer over gehoord). 

Als ik moet afgaan van de afbeeldingen zou het fijner zijn als de spacing tussen de tekst wat groter zou zijn. Momenteel zit het heel erg dicht op elkaar:
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/58737124/164acb0b-34fa-4f0f-821c-b84f3eeda5ae)

Het is ook netter om na 'Hallo,' en 'Met vriendelijke groeten,' wat whitespace achter te laten, dat ziet er wat netter uit.

_Hallo,_
.
_[inhoud]_
.
.
_Met vriendelijke groeten,_
.
_Scouting AZG_

Ook in de mail van de de bestelling annuleren zou ik er zelf ook de producten bij zetten, maar eventueel is het ordernummer ook genoeg.

Qua code ziet het er goed uit!

2024-06-13 16:39 UTC, Auwburn commented on resources/views/orders/emails/order_placed_success.blade.php
> +            <td>{{ \Carbon\Carbon::parse($order->order_date)->format('Y-m-d') }}</td>
Je kan voor de formatting van de datum ook __('common.date') gebruiken

2024-06-13 16:39 UTC, Auwburn commented on resources/views/orders/emails/orderstatus_changed.blade.php
> +            <td>{{ \Carbon\Carbon::parse($order->order_date)->format('Y-m-d') }}</td>
Hier geldt hetzelfde betreft de formatting

2024-06-14 12:32 UTC, VindSent commented
Ik heb de mails aangepast

### - Statusverandering
![Schermafbeelding 2024-06-14 142850](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/104061744/4f43a907-6a90-4742-8e5c-6ed74830bc62)

### - Bestelling plaatsen
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/104061744/015221ab-68af-4b3a-ad17-07eb5b4ac2e4)

### - Bestelling annuleren
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/104061744/1ecbf21b-0c81-4a11-bd06-89c59af2585e)

2024-06-14 15:46 UTC, Auwburn approved these changes
Ziet er goed uit!

2024-06-14 15:47 UTC, merged