feat(roles): new frontend + start of backend
Avans-290IN4SOj-Scouting/Scouting pull request #116
Opened 2024-06-04 13:01 UTC by Auwburn

_Naam van de branch is een beetje misleidend, er zit nog niet al te veel backend in._

Dit is een volledige revamp van de account promoveren pagina. Momentele is dit vooral frontend functionaliteit en een begin voor de backend. Hierdoor doen de filter- en zoekopties het nog niet. Ook kun je niet opslaan in de modal; dit wordt geïmplementeerd in de backend.

Het volgende zit hierin:
**Nieuw plusje:** als je hierop klikt komt er een select. Als je op deze select druk komt er een select (tag voor admin) in de rij.
**Select:** per groep/subrol is er een select aanwezig. Dit is geen multiple select omdat deze ik er in JS niet in kreeg. De keuzes zijn altijd uniek per rij; je kan niet twee keer Bevers A kiezen bijv.
**Keuzes onthouden:** keuzes worden onthouden (ook als je van pagina's wisselt). Deze kunnen weer reset worden door op 'wijzigingen ongedaan maken' te drukken.
**Checks:** er zijn checks aanwezig. Net als voorheen is er een check aanwezig die ervoor zorgt dat je niet kan opslaan als er geen veranderingen zijn. Ook is er een check aanwezig voor als je een groep probeert toe te voegen terwijl alle opties al gekozen zijn.
**Toast:** Ik heb toast.js ook aangepast, zodat een toast gebruikt wordt die vergelijkbaar is met het toast component in resources.

_Note: admin is in kleine letters. Dit komt omdat de display naam van de admin ook met een kleine letter is. Aangezien ik de seeders nog niet wil aanpassen (niet de bedoeling van deze PR) heb ik dit even achterwege gelaten._

2024-06-04 18:19 UTC, linderus commented
Something went wrong.... ik krijg de volgende errors in de console en als ik iets uit de dropdown selecteer gebeurt er niks, ook als ik op de opslaan knop druk....
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/130562052/36b63115-c3f1-4a86-8c52-42499778867a)

2024-06-04 18:30 UTC, linderus requested changes
Ziet er prima uit! Wel 2 opmerkingen over de toast;
- Door de veranderingen werkt de toast niet meer bij het toevoegen van een product aan de winkelwagen
- Na het streepje in de js toast staat geen spatie

2024-06-04 19:20 UTC, Auwburn commented
> Ziet er prima uit! Wel 2 opmerkingen over de toast;
> 
>     * Door de veranderingen werkt de toast niet meer bij het toevoegen van een product aan de winkelwagen
> 
>     * Na het streepje in de js toast staat geen spatie

oh natuurlijk! helemaal vergeten, ik zal dat morgen wel even fixen!

2024-06-05 10:52 UTC, linderus commented on database/seeders/DatabaseSeeder.php
Moet dit meegepusht worden?

2024-06-05 11:06 UTC, Auwburn commented on database/seeders/DatabaseSeeder.php
Voor nu wel, aangezien ik dit had gedaan om de lijst schoon te houden. 

Zelf wil ik de user rol weg hebben, maar ik weet niet of andere code afhankelijk is van die rol

2024-06-05 11:07 UTC, linderus commented on database/seeders/DatabaseSeeder.php
Alright, dan is t prima zo :)

2024-06-05 11:07 UTC, linderus approved these changes
Toppie

2024-06-05 11:09 UTC, merged