feat(admin): admin product management frontend
Avans-290IN4SOj-Scouting/Scouting pull request #71
Opened 2024-04-21 12:10 UTC by VindSent

2024-04-21 13:01 UTC, Auwburn requested changes
Goed begin! Ik heb nog wel wat feedback achtergelaten, maar veel ervan zijn vrij snel op te lossen!

2024-04-21 13:01 UTC, Auwburn commented on resources/views/admin/products.blade.php
> +                                            <input class="p-0 w-6 bg-transparent border-0 text-gray-800 text-center dark:text-white" type="text" value="0" data-hs-input-number-input="">
Zorg ervoor dat input ook een id heeft wat overeenkomt met de 'for' van het label. Momenteel krijg ik een 'input has no label' warning.

2024-04-21 13:01 UTC, Auwburn commented on resources/views/admin/products.blade.php
Ik zie hier heel veel herhalende code, waardoor de file echt heel groot is geworden. Probeer herhalende code in 'for' of 'foreach' te stoppen.

2024-04-21 13:01 UTC, Auwburn commented on resources/views/admin/products.blade.php
> +                    <hr class="border-gray-500">
Deze border is nog steeds zichtbaar wanneer de accordion ingeklapt is. Misschien zou je dit kunnen oplossen met JS?

2024-04-21 13:01 UTC, Auwburn commented on resources/views/admin/products.blade.php
> +                    <hr class="border-gray-500">
Zelfde geldt voor deze border

2024-04-21 13:01 UTC, Auwburn commented on resources/views/admin/products.blade.php
Momenteel ziet deze input er zo uit als ik erop focus. 

![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/58737124/68d6d7a2-f4e0-4f57-b037-6f01fcf5cf81)

Dit zou je op kunnen lossen door deze klassen aan de input velden toe te voegen:

```html
focus:rounded-l-none focus:rounded-r-lg
```

Dan komt het er zo uit te zien

![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/58737124/eb8d5644-6801-40d2-9792-9eb9aa441eb4)

2024-04-21 13:01 UTC, Auwburn commented on resources/views/admin/products.blade.php
Zelf gebruiken wij ```border-gray-200``` voor de kleur van de randen. Dan zijn de randen deze kleur in lightmode:

![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/58737124/2ce3bf3e-aace-4400-ab00-fbefd98e771a)

2024-04-21 13:01 UTC, Auwburn commented on resources/views/admin/products.blade.php
> +                        </button>
Ik zou zelf ```focus:text-blue-600``` aan de button class toevoegen om het meer zoals het ontwerp te maken.

2024-04-21 13:01 UTC, Auwburn commented on resources/views/admin/products.blade.php
> +                                </button>
Voor alle tussenkopjes zou ik alle tekst ```text-gray-500``` als kleur geven.

2024-04-21 13:01 UTC, Auwburn commented on resources/views/admin/products.blade.php
> +                                            </label>
Geef de labeltjes ```bg-gray-100``` of ```bg-gray-200``` om ze de grijze achtergrond te geven zoals in het ontwerp

2024-04-21 13:01 UTC, Auwburn commented on app/Http/Controllers/ManageProductsController.php
> +                'selected' => null
Wat is dit?

2024-04-21 13:04 UTC, VindSent commented on resources/views/admin/products.blade.php
Aangezien ik alleen bezig ben geweest met de frontend heb ik dit bewust gedaan zodat ik met de backend integratie dit gelijk goed kan doen.

2024-04-21 13:08 UTC, VindSent commented on app/Http/Controllers/ManageProductsController.php
> +                'selected' => null
Slordigheidsfoutje bij het kopiëren andere code.

2024-04-21 19:56 UTC, VindSent commented on resources/views/admin/products.blade.php
Heb nu een for loop per product, de loops voor de sizes komt wanneer ik de backend ga doen. Ik weet alleen niet hoe ik moet lopen over de kleuren, want nergens in de db zie ik een kolom of tabel die color heet.

2024-04-23 11:15 UTC, Auwburn requested changes
De frontend ziet er goed uit en de pagina is responsive! Ik heb nog wel wat functionele bugs gevonden.

2024-04-23 11:15 UTC, Auwburn commented on resources/views/admin/products.blade.php
Als ik een product openklap, en daarna een andere openklap, dan blijft het symbool van het eerste product een +

2024-04-23 11:15 UTC, Auwburn commented on public/js/manage-products/products.js
Als ik een product opengeklapt heb en daarna een ander product openklap, dan wordt de border niet op hidden gezet.

2024-04-23 11:15 UTC, Auwburn commented on public/js/manage-products/products.js
Er is een probleem dat meerdere product accordions open kunnen blijven staan.

Dit kun je reproduceren door dit te doen:

1. Klap product 1 open.
2. Klap een kleur van product 1 open.
3. Klap product 2 open.
4. Klap een kleur van product 2 open.
5. Klik weer op product 1.

2024-04-29 20:46 UTC, VindSent commented on public/js/manage-products/products.js
Nu blijven ze open staan en moet je ze zelf weer sluiten. Dit is omdat ik en Jeroen ervoor hebben gekozen niet de accordion te gebruiken omdat daar bugs in zitten en preline geen goed voorbeeld heeft van twee of meer hoofdaccordions die meerdere subaccordions hebben.

2024-04-30 13:41 UTC, Auwburn requested changes
Ik heb nog een paar opmerkingen. Als die opgelost zijn kan ik het goedkeuren!

2024-04-30 13:41 UTC, Auwburn commented on resources/views/admin/products.blade.php
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/58737124/6fa960e4-039f-4469-aa66-77f3a3b8e89e)

Ik krijg 100 errors in inspector. 

Gedetailleerde errormessages:
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/58737124/de64d20f-8a41-484a-b403-da1ebd3d4b3e)
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/58737124/0aa81959-7bb9-4432-bb7a-197af88fb3e9)

2024-04-30 13:41 UTC, Auwburn commented on resources/views/admin/products.blade.php
In lightmode zijn niet alle borders zichtbaar zoals in dark mode. Om het consistent te houden raad ik aan om hier alsnog borders aan toe te voegen.

![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/58737124/40529a31-5f69-4037-91c3-805a5bd5cdc9)

2024-04-30 13:41 UTC, Auwburn commented on resources/views/admin/products.blade.php
> +                                        Opslaan
Gebruik hiervoor localisatie

2024-04-30 20:30 UTC, VindSent commented on resources/views/admin/products.blade.php
Gefixt kon niet zien het er in lightmode eruit zag, had al geprobeerd dat in mjin browser aan te passen, maar lag aan het OS.

2024-05-01 18:27 UTC, Auwburn approved these changes
Alle feedback is goed verwerkt. Top!

2024-05-01 18:27 UTC, merged