feat(manage-account): frontend, backend, tests
Avans-290IN4SOj-Scouting/Scouting pull request #75
Opened 2024-04-23 18:41 UTC by linderus

2024-04-23 19:35 UTC, Auwburn requested changes
Ik heb nog iets gevonden in de view wat ik de vorige keer over het hoofd heb gezien. Verder is er nog iets mis met een test van een ander onderdeel.

2024-04-23 19:35 UTC, Auwburn commented on resources/views/profile/edit.blade.php
Eén heel klein dingetje. Momenteel zien de order-previews er zo uit op xs (screenshot omdat de orders net niet te zien waren in de test screenshots). Misschien is het mooier als ze net zo breed zijn als de knoppen of dat ze gecentreerd staan.

![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/58737124/3b09e732-1bab-468a-9e58-aa0f39d8fb8f)

2024-04-23 19:35 UTC, Auwburn commented on tests/Feature/ProfileTest.php
Deze test slaagt, maar een andere test is kapot gegaan:

![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/58737124/dfca0592-cc4b-4a76-8019-bd77c1f5370c)

2024-04-23 19:37 UTC, linderus commented on tests/Feature/ProfileTest.php
Klopt, die is al in dev gefixt. Zal die ff pullen

2024-04-23 19:37 UTC, linderus commented on resources/views/profile/edit.blade.php
Ga het nu verwerken!

2024-04-24 07:56 UTC, Auwburn requested changes
Nog één ding, maar ik heb al wat codesnippets meegegeven! (Als je de oplossing prima vindt, kan ik mijn aanpassingen gewoon committen :) )

2024-04-24 07:56 UTC, Auwburn commented on resources/views/profile/edit.blade.php
Hmmm, nu hebben de elementen allemaal verschillende breedtes. Dat vind ik zelf niet zo mooi. Ik heb nog even gekeken naar de code en heb het volgende veranderd:

Ik heb ```max-w-sm``` verwijderd in order-preview.blade

```html
<div class="w-full sm:flex sm:max-w-none border border-gray-300 dark:border-gray-700 rounded-xl overflow-hidden">
```

En ```max-sm:items-center``` weggehaald uit edit.blade.php

```html
<div class="flex flex-col pt-4 gap-4">
```

Ik heb getest of dit ook de rest van de responsiveness aanpast en bij mij ziet alles er hetzelfde uit. De xs-variant van de pagina ziet er nu zo uit:

![afbeelding](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/58737124/84d07006-2c84-42ef-b73e-e727252f5bf4)

De tekst is alleen niet zo goed leesbaar, maar ik ga ervan uit dat dit placeholders zijn voor foto's.

2024-04-24 08:04 UTC, Auwburn approved these changes
Top!

2024-04-24 08:05 UTC, merged