feat(profile)order-overview
Avans-290IN4SOj-Scouting/Scouting pull request #77
Opened 2024-04-24 21:06 UTC by lilHerbie

2024-04-25 17:57 UTC, linderus requested changes
Wat je eigenlijk in het overzicht doet is alle orders ophalen, ik ben dus van mening dat die code in de `ProfileController` niet echt passend is en beter in `OrderController` kan. Ook de view kan dan beter in een andere folder + hetzelfde voor de route

2024-04-25 17:57 UTC, linderus commented on resources/views/profile/edit.blade.php
> +</div>
Ik vind een breadcrump hier niet passend, want het is niet echt een subpagina

2024-04-25 17:57 UTC, linderus commented on resources/views/profile/overview.blade.php
> +    $title = __('order_tracking.order_tracking_title');
Deze lokalisatie klopt niet

2024-04-25 17:57 UTC, linderus commented on resources/views/profile/overview.blade.php
De breadcrump vind ik niet zo mooi, doordat de tekst geen hoofdletters bevat (behalve Home, alleen die kan weg)

2024-04-25 17:57 UTC, linderus commented on resources/views/profile/overview.blade.php
> +        @endforeach
Kan je hier alvast ervoor zorgen dat het een link is die naar # leidt? Net zoals in edit.blade.php.

2024-05-01 16:59 UTC, lilHerbie commented
Ik heb de feedback van Linder verwerkt dus hij kan opnieuw gereviewd woden

2024-05-02 16:56 UTC, linderus requested changes
Ik denk dat doordat je niet up-to-date bent met dev je in de frontend geen mooie kleuren ziet voor de bestelstatus, als het na mergen nog steeds niet goed is, dan heb jij ergens die code aangepast dus moet dat nog ff opgelost worden

2024-05-02 16:56 UTC, linderus commented on routes/web.php
> +        ->name('overviewMyOrders');
Deze route name is niet consistent met de rest

2024-05-02 16:58 UTC, linderus reviewed
Kan je ook de lokalisatie consistent maken? Soms doe je met een laag streepje ertussen, soms een streepje en soms camelcase, kan je het allemaal met laag streepje doen?

2024-05-06 16:23 UTC, linderus requested changes
Ik heb nog een paar opmerkingen achtergelaten, ook mis ik nog dusk en feature testen

2024-05-06 16:23 UTC, linderus commented on app/Http/Controllers/OrderController.php
> +            return redirect()->route('orders.overview_admin');
```suggestion
            return redirect()->route('orders.overview.admin');
```

2024-05-06 16:23 UTC, linderus commented on lang/nl/route.php
> +    "overview_user" => "overzicht-bestellingen",
Je kan gewoon "overview" doen, en die in de route prefix gebruiken. Dan heb je:
http://127.0.0.1:8000/producten/overzicht/Kabouters
en
http://127.0.0.1:8000/bestelling/overzicht
Ook is vgm dat overview niet alleen voor de admin, maar voor het overzicht van producten

2024-05-06 16:23 UTC, linderus commented on resources/views/orders/overview-user.blade.php
> +            <a href="#">
OrderDetails staat nu wel op dev, dus daar kan je deze naar linken

2024-05-14 12:05 UTC, JrnJ commented
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/60579554/54fc4d67-9ac9-4985-aa77-e1dc051f0e3d)
Hier zou nog een titel tussen kunnen

2024-05-14 12:06 UTC, JrnJ commented
Ik weet niet wat het is, maar de navbar "Home" tekst gaat een stukje naar links op je pagina

2024-05-14 12:12 UTC, JrnJ commented on app/Http/Controllers/OrderController.php
> +            $order->order_date = new \DateTime($order->order_date);
We gebruiken normaal Carbon, ik weet niet of dit wat uit maakt.

2024-05-16 15:16 UTC, JrnJ approved these changes
lgtm

2024-05-16 15:20 UTC, merged