fix(product): softdelete products
Avans-290IN4SOj-Scouting/Scouting pull request #82
Opened 2024-05-03 18:02 UTC by Neverless90

2024-05-03 20:57 UTC, Auwburn requested changes
Aangezien dit mijn code is heb ik enige oplossingen meegegeven. Echter, de branch is 21 dagen oud en zwaar verouderd. Deze moet geupdate worden naar de laatste versie van productpage-v-detached. Ik weet niet wat er gebeurt met mijn oplossingen als de branch geupdate wordt

2024-05-03 20:57 UTC, Auwburn commented on lang/nl/products.php
Deze berichten zijn wat duidelijker:

```php
'inactive-product' => 'Momenteel actief. Klik om inactief te maken.',
'active-product' => 'Momenteel inactief. Klik om actief te maken.',

2024-05-03 20:57 UTC, Auwburn commented on resources/views/admin/EditProduct.blade.php
> +                        @endif
Om duplicate code te voorkomen kun je het refactoren naar dit:

```php
<input name="inactive-checkbox" type="checkbox"
                               class="shrink-0 mt-0.5 border-gray-200 rounded text-blue-600 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-gray-800 dark:border-gray-700 dark:checked:bg-blue-500 dark:checked:border-blue-500 dark:focus:ring-offset-gray-800"
                               id="hs-default-checkbox" {{ $product->inactive ? 'checked' : '' }}>
                        <label for="hs-default-checkbox"
                               class="text-sm text-gray-500 ms-3 dark:text-gray-400">
                            {{ $product->inactive ? __('products.active-product') : __('products.inactive-product') }}
                        </label>

2024-05-03 20:57 UTC, Auwburn commented on tests/Feature/ProductUpdateTest.php
> +                'inactive' => 'true'
Verander dit naar ```'inactive-checkbox' => 'true'```

2024-05-09 15:32 UTC, closed without merging

2024-05-09 15:32 UTC, Neverless90 commented
Veranderingen overgenomen naar een andere branch, nog bedankt Delite trouwens!