feat(groupleader orders): groepleader can see orders of their group(s)
Avans-290IN4SOj-Scouting/Scouting pull request #88
Opened 2024-05-10 10:45 UTC by JrnJ

Login:
groepsleider@azge.nl
password

Je kan rollen aanpassen in UserWithRoleSeeder.php

2024-05-11 20:24 UTC, VindSent approved these changes

2024-05-11 21:08 UTC, linderus requested changes
Ik zie dat deze PR al geaccepteerd is maar er vielen mij wat dingetjes op dus heb ik toch maar achtergelaten

2024-05-11 21:08 UTC, linderus commented on app/Http/Controllers/ManageOrdersController.php
> +        }
Precies hetzelfde doe je ook op line 19 t/m 21. Misschien iets van een functie maken voor het ophalen van de Orders?

2024-05-11 21:08 UTC, linderus commented on resources/views/admin/orders.blade.php
> +                    </th>
Aangezien dit nu in het overzicht toegevoegd is, vind ik het wel passend als hier een zoek- en/of sorteerfilter op komt. Ik heb het idee dat Ivo hier een opmerking over gaat geven (wat ik ook snap)

2024-05-11 21:08 UTC, linderus commented on database/migrations/2024_05_10_110438_add_group_id_to_role.php
> +            $table->foreignId('group_id')->nullable();
Ik weet niet precies hoe het komt, alleen er is geen correcte link in de db tussen roles en group(id)

2024-05-14 08:48 UTC, linderus approved these changes
lgtm!

2024-05-14 09:18 UTC, merged