Feat/schrijf backend soj 35
Avans-290IN4SOj-Scouting/Scouting pull request #91
Opened 2024-05-10 14:33 UTC by VindSent

2024-05-11 22:00 UTC, linderus requested changes
Ik heb wat comments achtergelaten

2024-05-11 22:00 UTC, linderus commented on app/Http/Controllers/ManageStocksController.php
Suggestie:
`ManageStocksController -> StocksController`

2024-05-11 22:00 UTC, linderus commented on app/Http/Controllers/ManageStocksController.php
> +        return view("admin.stocks", ['products' => $products]);
Dubbele haakjes gebruik je het liefste alleen voor string interpolation
```suggestion
        return view('admin.stocks', ['products' => $products]);
```

2024-05-11 22:00 UTC, linderus commented on resources/views/admin/stocks.blade.php
Deze pagina heb je nu renamed, maar je moet een nieuwe blade file aanmaken waarin je deze frontend zet. Door dit te doen krijgen we onnodige merge conflicts in andere PR's

2024-05-11 22:00 UTC, linderus commented on resources/views/admin/stocks.blade.php
> +                {{--                @endforeach--}}
?

2024-05-11 22:00 UTC, linderus commented on routes/web.php
> +        //TODO: remove this before merging into develop
Waarom heb je dit allemaal uitgecomment?

2024-05-11 22:00 UTC, linderus commented on routes/web.php
> +        Route::prefix(__('navbar.manage_stocks'))->group(function () {
```suggestion
        Route::prefix(__('route.stocks'))->name('stocks.')->group(function () {
```
En vervolgens in route.php: `'stocks' => 'voorraad'`

2024-05-11 22:00 UTC, linderus commented on app/Http/Controllers/ManageStocksController.php
> +    public function update(Request $request, $id)
Je valideert nergens de data die je krijgt, ik kan nu letters invoeren en dan krijg ik een SQL-error, ook als ik een te groot getal in voer

2024-05-11 22:00 UTC, linderus commented on resources/views/admin/stocks.blade.php
Ik weet dat dit een PR is voor de backend, maar de frontend ziet er echt niet mooi uit in light mode. Ook gaat er iets mis met de border: 
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/130562052/663a3001-301b-475c-a7b6-a8f655f39939)

2024-05-11 22:00 UTC, linderus commented on app/Models/Order.php
> -    ];
Waarom heb je dit weggehaald?

2024-05-12 12:40 UTC, VindSent commented on routes/web.php
> +        //TODO: remove this before merging into develop
Dat waren de routes van Anton en Roy. Ik heb het weggehaald, want dat komt er dan bij het merge met develop erin.

2024-05-12 12:41 UTC, VindSent commented on app/Models/Order.php
> -    ];
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/104061744/137f5a23-d622-4dd1-a81e-44c278e0fd7b)

Er staat al een fillable

2024-05-12 20:20 UTC, linderus commented on resources/views/admin/stocks.blade.php
Je hebt deze resolved, maar ik zie geen verandering. De border van de accordeon is nog steeds zwart (Wat beter een grijs tint kan zijn) en hetzelfde probleem met het verdwijnen van een hoekje van de border is er nog.

2024-05-12 20:25 UTC, linderus commented on database/migrations/2024_02_28_125358_create_stocks_table.php
>              $table->integer('product_id');
`product_size_id` en `product_id` zijn geen integers, maar FK, nu is de link niet goed gelegd in de database

2024-05-12 20:29 UTC, linderus commented
Ik heb getest of het werkt als je bij een product meer dan 1 catergorie hebt, dat die dan onder dezelfde accordeon komt te staan. Dit blijkt in jouw code niet te werken:
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/130562052/4cc3222f-6992-4be7-b621-f882d4935c73)

2024-05-16 20:36 UTC, VindSent commented on resources/views/admin/stocks.blade.php
In light mode is de kleur van de rand #6b7280 wat wel lijkt op #000000.

![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/104061744/32452999-955e-488e-bee8-4cd5991da56c)

2024-05-17 14:44 UTC, linderus commented on app/Http/Controllers/StocksController.php
> +    public function update(Request $request, $productId, $productTypeId)
Waarom maak je niet gewoon een custom Request?

2024-05-17 14:45 UTC, linderus commented on app/Models/ProductCollection.php
Dit was toch de vorige oplossing?

2024-05-17 14:46 UTC, linderus commented on database/migrations/2024_05_16_210957_add_product_type_id_to_stocks_table.php
Vanwege versiegeschiedenis is het onverstandig om een migratie aan te passen, je kan beter een nieuwe migratie aanmaken, maar dat is voor een volgende

2024-05-17 14:47 UTC, linderus commented on database/seeders/ProductProductTypeSeeder.php
Als deze leeg blijft, kan je m beter verwijderen

2024-05-17 14:47 UTC, linderus commented on lang/nl/manage-stocks/stocks.php
> +    '"empty_inventory"' => "Weet je zeker dat je de voorraad wilt legen?",
```suggestion
    "empty_inventory" => "Weet je zeker dat je de voorraad wilt legen?",
```

2024-05-17 14:48 UTC, linderus requested changes
Frontend is nice zo en voor de backend heb ik wat comments achtergelaten. Je hebt wel ineens veel files, komt dat doordat de main branch niet up to date is met dev?

2024-05-17 14:52 UTC, linderus commented
Als ik van 1 maat de voorraad aanpas sla je alle maten op, zie screenshot:
![image](https://github.com/Avans-290IN4SOj-Scouting/Scouting/assets/130562052/f9ac7d6b-1f7d-4078-a6c1-5325ac84328c)

2024-05-17 16:15 UTC, VindSent commented on app/Models/ProductCollection.php
Ja, vergeten te verwijderen

2024-05-17 16:16 UTC, VindSent commented on database/migrations/2024_05_16_210957_add_product_type_id_to_stocks_table.php
Inderdaad, had ik geen rekening mee gehouden

2024-05-17 16:17 UTC, VindSent commented on database/seeders/ProductProductTypeSeeder.php
Ook deze ben ik vergeten

2024-05-17 16:32 UTC, VindSent commented
> Als ik van 1 maat de voorraad aanpas sla je alle maten op, zie screenshot: ![image](https://private-user-images.githubusercontent.com/130562052/331638066-f9ac7d6b-1f7d-4078-a6c1-5325ac84328c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NjM2MTcsIm5iZiI6MTcxNTk2MzMxNywicGF0aCI6Ii8xMzA1NjIwNTIvMzMxNjM4MDY2LWY5YWM3ZDZiLTFmN2QtNDA3OC1hNmMxLTUzMjVhYzg0MzI4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxNjI4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjM3YzkzNjdiODhmZmRjYTM3Yzc2YmE0YzQ1OWExNmUyZjQxYjY1YmExYjhmOWY2MzdlZDIyMDJiOGU2Nzg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ciOgdL4RfpDxJsup8-twA-kwha-uY_j5VlrIi9nxqlY)

Ik denk dat beter is omdat je zo alles maten van een type zo onder elkaar hebt staan in de tabel. Ook zou het dan lastiger worden om bij het bijwerken van de voorraad het aantal op 0 te zetten.

2024-05-17 20:36 UTC, linderus approved these changes
Prima!

2024-05-17 20:50 UTC, merged